name: Commit checker

on:
  pull_request:

jobs:
  commit-checker:
    name: Commit checker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pull-request
      run: |
        set -x

        env

        PR_NUMBER=$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")

        git version
        git init /home/runner/work/OpenTTD/OpenTTD
        git remote add origin https://github.com/OpenTTD/OpenTTD
        git config --local gc.auto 0

        # Query GitHub API to find out what the first commit of this pull-request is
        FIRST_REF=$(curl -X POST -v -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Content-Type: application/json" https://api.github.com/graphql \
          -d '{"query": "query { repository(owner: \"OpenTTD\", name:\"OpenTTD\") { pullRequest(number: '${PR_NUMBER}') { commits(first: 1) { nodes { commit { oid } } } } } }"}' \
          | jq .data.repository.pullRequest.commits.nodes[0].commit.oid | cut -d\" -f2)

        git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${FIRST_REF}
        git -c protocol.version=2 fetch --no-tags --prune --negotiation-tip=${FIRST_REF} origin +refs/pull/${PR_NUMBER}/head:pr/${PR_NUMBER}

    - name: Checkout commit-checker
      uses: actions/checkout@v2
      with:
        repository: OpenTTD/OpenTTD-git-hooks
        path: git-hooks
        ref: master

    - name: Check commits
      run: |
        HOOKS_DIR=./git-hooks/hooks GIT_DIR=.git ./git-hooks/hooks/check-commits.sh
        echo "Commit checks passed"
